# Generated by Django 4.1 on 2022-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
