# Generated by Django 4.1 on 2022-08-19 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
