# Generated by Django 4.1 on 2022-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
