# Generated by Django 4.1 on 2022-08-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='youtube',
        ),
    ]
