# Generated by Django 4.1 on 2022-08-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_created',
            new_name='created_date',
        ),
    ]
